# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/TSFM',
                'doc_host': 'https://fevzikilas.github.io',
                'git_url': 'https://github.com/fevzikilas/TSFM',
                'lib_path': 'TSFM'},
  'syms': {'TSFM.core': {'TSFM.core.foo': ('core.html#foo', 'TSFM/core.py')}}}
